##################################生产环境配置开始#######################
server:
  port: 8091

spring:
  datasource:
    url: jdbc:mysql://xx:3306/ryoma_co_ctms?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: xx
    password: xx
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    max-active: 200
    initial-size: 10
    validation-query: SELECT 1
    test-on-borrow: true
    test-while-idle: true
    time-between-eviction-runs-millis: 18800

  profiles: prod

  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    encoding: UTF-8
    mode: HTML5
    suffix: .html

  #mvc:
    #static-path-pattern: /static/**

mybatis:
  mapper-locations: classpath*:mapper/*.xml

#mqtt
mqtt_url: tcp://xx:1883
mqtt_clientId: weirdo-cliendId

#websocket
websocket_hostname: xx
websocket_port: 61614

#amq过期时间,防止积压(秒)
mqtt_expiration: 20

activemq:
  broker-url: tcp://139.9.6.82:61616
  user: admin
  password: admin

#防区半径
safeRadius: 500

#劳务管理
labor_service_url: 


